// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../model/entry/apps.dart';
import '../model/entry/clipboard_entry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1029841517966745771),
    name: 'Apps',
    lastPropertyId: const obx_int.IdUid(4, 2452848880980080350),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5455871040319878887),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5108568063121421747),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6119588509805439348),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2452848880980080350),
        name: 'url',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1887858096857783361),
    name: 'ClipboardEntity',
    lastPropertyId: const obx_int.IdUid(9, 8860892259710238831),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 918809459121387394),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8757663381395322072),
        name: 'idx',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 3104376604868673414),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6407211722903036216),
        name: 'tag',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 132153700579546417),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8569554793260514582),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7769992134019030645),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2874451613741067049),
        name: 'content',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 746699406087926362),
        name: 'hash',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 700727458187210988),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7173285756297615058),
        name: 'size',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8860892259710238831),
        name: 'type',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 1887858096857783361),
    lastIndexId: const obx_int.IdUid(9, 6566641600457918791),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      8853705555893745235,
      2813412396149084478,
      8429156918514459688,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1071601446320569851,
      1985560521931788342,
      1413168206057090159,
      7746411159101834937,
      7984932927947789430,
      7045164783029529542,
      4365034224799355876,
      1379390773973153927,
      1089723352459954443,
      3546598700747665471,
      8495882089045527735,
      2422208534410267481,
      4707409794687408145,
      8009509438762341570,
      5819721364501258297,
      4354847269640612564,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Apps: obx_int.EntityDefinition<Apps>(
      model: _entities[0],
      toOneRelations: (Apps object) => [],
      toManyRelations: (Apps object) => {},
      getId: (Apps object) => object.id,
      setId: (Apps object, int id) {
        object.id = id;
      },
      objectToFB: (Apps object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        final urlOffset = fbb.writeString(object.url);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, iconOffset);
        fbb.addOffset(3, urlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = Apps(
          idParam,
          name: nameParam,
          icon: iconParam,
          url: urlParam,
        );

        return object;
      },
    ),
    ClipboardEntity: obx_int.EntityDefinition<ClipboardEntity>(
      model: _entities[1],
      toOneRelations: (ClipboardEntity object) => [],
      toManyRelations: (ClipboardEntity object) => {},
      getId: (ClipboardEntity object) => object.id,
      setId: (ClipboardEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ClipboardEntity object, fb.Builder fbb) {
        final idxOffset = fbb.writeString(object.idx);
        final tagOffset = fbb.writeString(object.tag);
        final sourceOffset = fbb.writeString(object.source);
        final contentOffset = fbb.writeListInt8(object.content);
        final hashOffset = fbb.writeString(object.hash);
        final typeOffset = fbb.writeString(object.type);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, idxOffset);
        fbb.addOffset(2, tagOffset);
        fbb.addInt64(3, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.addOffset(4, sourceOffset);
        fbb.addOffset(5, contentOffset);
        fbb.addOffset(6, hashOffset);
        fbb.addInt64(7, object.size);
        fbb.addOffset(8, typeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ClipboardEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..idx = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..tag = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..updatedAt = DateTime.fromMicrosecondsSinceEpoch(
            (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
                .round(),
          )
          ..source = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..content =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGet(buffer, rootOffset, 14, Uint8List(0))
                  as Uint8List
          ..hash = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..size = const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
          ..type = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Apps] entity fields to define ObjectBox queries.
class Apps_ {
  /// See [Apps.id].
  static final id = obx.QueryIntegerProperty<Apps>(_entities[0].properties[0]);

  /// See [Apps.name].
  static final name = obx.QueryStringProperty<Apps>(_entities[0].properties[1]);

  /// See [Apps.icon].
  static final icon = obx.QueryStringProperty<Apps>(_entities[0].properties[2]);

  /// See [Apps.url].
  static final url = obx.QueryStringProperty<Apps>(_entities[0].properties[3]);
}

/// [ClipboardEntity] entity fields to define ObjectBox queries.
class ClipboardEntity_ {
  /// See [ClipboardEntity.id].
  static final id = obx.QueryIntegerProperty<ClipboardEntity>(
    _entities[1].properties[0],
  );

  /// See [ClipboardEntity.idx].
  static final idx = obx.QueryStringProperty<ClipboardEntity>(
    _entities[1].properties[1],
  );

  /// See [ClipboardEntity.tag].
  static final tag = obx.QueryStringProperty<ClipboardEntity>(
    _entities[1].properties[2],
  );

  /// See [ClipboardEntity.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<ClipboardEntity>(
    _entities[1].properties[3],
  );

  /// See [ClipboardEntity.source].
  static final source = obx.QueryStringProperty<ClipboardEntity>(
    _entities[1].properties[4],
  );

  /// See [ClipboardEntity.content].
  static final content = obx.QueryByteVectorProperty<ClipboardEntity>(
    _entities[1].properties[5],
  );

  /// See [ClipboardEntity.hash].
  static final hash = obx.QueryStringProperty<ClipboardEntity>(
    _entities[1].properties[6],
  );

  /// See [ClipboardEntity.size].
  static final size = obx.QueryIntegerProperty<ClipboardEntity>(
    _entities[1].properties[7],
  );

  /// See [ClipboardEntity.type].
  static final type = obx.QueryStringProperty<ClipboardEntity>(
    _entities[1].properties[8],
  );
}
