// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../model/entry/apps.dart';
import '../model/entry/clipboards.dart';
import '../model/entry/record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1029841517966745771),
    name: 'Apps',
    lastPropertyId: const obx_int.IdUid(4, 2452848880980080350),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5455871040319878887),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5108568063121421747),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6119588509805439348),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2452848880980080350),
        name: 'url',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2813412396149084478),
    name: 'Clipboards',
    lastPropertyId: const obx_int.IdUid(5, 1379390773973153927),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7746411159101834937),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7984932927947789430),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7045164783029529542),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4365034224799355876),
        name: 'updatedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1379390773973153927),
        name: 'appsId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 5417029971902208060),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8853705555893745235),
    name: 'Record',
    lastPropertyId: const obx_int.IdUid(3, 1413168206057090159),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1071601446320569851),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1985560521931788342),
        name: 'clipboardsId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1413168206057090159),
        name: 'content',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8853705555893745235),
    lastIndexId: const obx_int.IdUid(1, 5417029971902208060),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Apps: obx_int.EntityDefinition<Apps>(
      model: _entities[0],
      toOneRelations: (Apps object) => [],
      toManyRelations: (Apps object) => {},
      getId: (Apps object) => object.id,
      setId: (Apps object, int id) {
        object.id = id;
      },
      objectToFB: (Apps object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        final urlOffset = fbb.writeString(object.url);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, iconOffset);
        fbb.addOffset(3, urlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = Apps(
          idParam,
          name: nameParam,
          icon: iconParam,
          url: urlParam,
        );

        return object;
      },
    ),
    Clipboards: obx_int.EntityDefinition<Clipboards>(
      model: _entities[1],
      toOneRelations: (Clipboards object) => [],
      toManyRelations: (Clipboards object) => {},
      getId: (Clipboards object) => object.id,
      setId: (Clipboards object, int id) {
        object.id = id;
      },
      objectToFB: (Clipboards object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final updatedAtOffset = fbb.writeString(object.updatedAt);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addOffset(2, createdAtOffset);
        fbb.addOffset(3, updatedAtOffset);
        fbb.addInt64(4, object.appsId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final updatedAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final appsIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Clipboards(
          typeParam,
          createdAtParam,
          updatedAtParam,
          appsIdParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Record: obx_int.EntityDefinition<Record>(
      model: _entities[2],
      toOneRelations: (Record object) => [],
      toManyRelations: (Record object) => {},
      getId: (Record object) => object.id,
      setId: (Record object, int id) {
        object.id = id;
      },
      objectToFB: (Record object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.clipboardsId);
        fbb.addOffset(2, contentOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final clipboardsIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Record(idParam, clipboardsIdParam, contentParam);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Apps] entity fields to define ObjectBox queries.
class Apps_ {
  /// See [Apps.id].
  static final id = obx.QueryIntegerProperty<Apps>(_entities[0].properties[0]);

  /// See [Apps.name].
  static final name = obx.QueryStringProperty<Apps>(_entities[0].properties[1]);

  /// See [Apps.icon].
  static final icon = obx.QueryStringProperty<Apps>(_entities[0].properties[2]);

  /// See [Apps.url].
  static final url = obx.QueryStringProperty<Apps>(_entities[0].properties[3]);
}

/// [Clipboards] entity fields to define ObjectBox queries.
class Clipboards_ {
  /// See [Clipboards.id].
  static final id = obx.QueryIntegerProperty<Clipboards>(
    _entities[1].properties[0],
  );

  /// See [Clipboards.type].
  static final type = obx.QueryStringProperty<Clipboards>(
    _entities[1].properties[1],
  );

  /// See [Clipboards.createdAt].
  static final createdAt = obx.QueryStringProperty<Clipboards>(
    _entities[1].properties[2],
  );

  /// See [Clipboards.updatedAt].
  static final updatedAt = obx.QueryStringProperty<Clipboards>(
    _entities[1].properties[3],
  );

  /// See [Clipboards.appsId].
  static final appsId = obx.QueryIntegerProperty<Clipboards>(
    _entities[1].properties[4],
  );
}

/// [Record] entity fields to define ObjectBox queries.
class Record_ {
  /// See [Record.id].
  static final id = obx.QueryIntegerProperty<Record>(
    _entities[2].properties[0],
  );

  /// See [Record.clipboardsId].
  static final clipboardsId = obx.QueryIntegerProperty<Record>(
    _entities[2].properties[1],
  );

  /// See [Record.content].
  static final content = obx.QueryStringProperty<Record>(
    _entities[2].properties[2],
  );
}
