// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../model/entry/apps.dart';
import '../model/entry/clipboards.dart';
import '../model/entry/record_content.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1029841517966745771),
    name: 'Apps',
    lastPropertyId: const obx_int.IdUid(4, 2452848880980080350),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5455871040319878887),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5108568063121421747),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6119588509805439348),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2452848880980080350),
        name: 'url',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2813412396149084478),
    name: 'Clipboards',
    lastPropertyId: const obx_int.IdUid(8, 8495882089045527735),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7746411159101834937),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7984932927947789430),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7045164783029529542),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4365034224799355876),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1379390773973153927),
        name: 'appsId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 5417029971902208060),
        relationField: 'apps',
        relationTarget: 'Apps',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1089723352459954443),
        name: 'idx',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 7915215574012673153),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3546598700747665471),
        name: 'tag',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 106569065744668616),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8495882089045527735),
        name: 'recordContentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 1702022961805575518),
        relationField: 'recordContent',
        relationTarget: 'RecordContent',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8429156918514459688),
    name: 'RecordContent',
    lastPropertyId: const obx_int.IdUid(5, 4354847269640612564),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2422208534410267481),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4707409794687408145),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8009509438762341570),
        name: 'clipboardsId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 218283363638483268),
        relationField: 'clipboards',
        relationTarget: 'Clipboards',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5819721364501258297),
        name: 'hash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4354847269640612564),
        name: 'length',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8429156918514459688),
    lastIndexId: const obx_int.IdUid(5, 1702022961805575518),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [8853705555893745235],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1071601446320569851,
      1985560521931788342,
      1413168206057090159,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Apps: obx_int.EntityDefinition<Apps>(
      model: _entities[0],
      toOneRelations: (Apps object) => [],
      toManyRelations: (Apps object) => {},
      getId: (Apps object) => object.id,
      setId: (Apps object, int id) {
        object.id = id;
      },
      objectToFB: (Apps object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        final urlOffset = fbb.writeString(object.url);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, iconOffset);
        fbb.addOffset(3, urlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = Apps(
          idParam,
          name: nameParam,
          icon: iconParam,
          url: urlParam,
        );

        return object;
      },
    ),
    Clipboards: obx_int.EntityDefinition<Clipboards>(
      model: _entities[1],
      toOneRelations: (Clipboards object) => [
        object.apps,
        object.recordContent,
      ],
      toManyRelations: (Clipboards object) => {},
      getId: (Clipboards object) => object.id,
      setId: (Clipboards object, int id) {
        object.id = id;
      },
      objectToFB: (Clipboards object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final idxOffset = fbb.writeString(object.idx);
        final tagOffset = fbb.writeString(object.tag);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addInt64(2, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(3, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(4, object.apps.targetId);
        fbb.addOffset(5, idxOffset);
        fbb.addOffset(6, tagOffset);
        fbb.addInt64(7, object.recordContent.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Clipboards()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..type = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..createdAt = DateTime.fromMicrosecondsSinceEpoch(
            (const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0) / 1000)
                .round(),
          )
          ..updatedAt = DateTime.fromMicrosecondsSinceEpoch(
            (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
                .round(),
          )
          ..idx = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..tag = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '');
        object.apps.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.apps.attach(store);
        object.recordContent.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.recordContent.attach(store);
        return object;
      },
    ),
    RecordContent: obx_int.EntityDefinition<RecordContent>(
      model: _entities[2],
      toOneRelations: (RecordContent object) => [object.clipboards],
      toManyRelations: (RecordContent object) => {},
      getId: (RecordContent object) => object.id,
      setId: (RecordContent object, int id) {
        object.id = id;
      },
      objectToFB: (RecordContent object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final hashOffset = fbb.writeString(object.hash);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.clipboards.targetId);
        fbb.addOffset(3, hashOffset);
        fbb.addInt64(4, object.length);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = RecordContent()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..content = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..hash = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..length = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );
        object.clipboards.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.clipboards.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Apps] entity fields to define ObjectBox queries.
class Apps_ {
  /// See [Apps.id].
  static final id = obx.QueryIntegerProperty<Apps>(_entities[0].properties[0]);

  /// See [Apps.name].
  static final name = obx.QueryStringProperty<Apps>(_entities[0].properties[1]);

  /// See [Apps.icon].
  static final icon = obx.QueryStringProperty<Apps>(_entities[0].properties[2]);

  /// See [Apps.url].
  static final url = obx.QueryStringProperty<Apps>(_entities[0].properties[3]);
}

/// [Clipboards] entity fields to define ObjectBox queries.
class Clipboards_ {
  /// See [Clipboards.id].
  static final id = obx.QueryIntegerProperty<Clipboards>(
    _entities[1].properties[0],
  );

  /// See [Clipboards.type].
  static final type = obx.QueryStringProperty<Clipboards>(
    _entities[1].properties[1],
  );

  /// See [Clipboards.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<Clipboards>(
    _entities[1].properties[2],
  );

  /// See [Clipboards.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<Clipboards>(
    _entities[1].properties[3],
  );

  /// See [Clipboards.apps].
  static final apps = obx.QueryRelationToOne<Clipboards, Apps>(
    _entities[1].properties[4],
  );

  /// See [Clipboards.idx].
  static final idx = obx.QueryStringProperty<Clipboards>(
    _entities[1].properties[5],
  );

  /// See [Clipboards.tag].
  static final tag = obx.QueryStringProperty<Clipboards>(
    _entities[1].properties[6],
  );

  /// See [Clipboards.recordContent].
  static final recordContent =
      obx.QueryRelationToOne<Clipboards, RecordContent>(
        _entities[1].properties[7],
      );
}

/// [RecordContent] entity fields to define ObjectBox queries.
class RecordContent_ {
  /// See [RecordContent.id].
  static final id = obx.QueryIntegerProperty<RecordContent>(
    _entities[2].properties[0],
  );

  /// See [RecordContent.content].
  static final content = obx.QueryStringProperty<RecordContent>(
    _entities[2].properties[1],
  );

  /// See [RecordContent.clipboards].
  static final clipboards = obx.QueryRelationToOne<RecordContent, Clipboards>(
    _entities[2].properties[2],
  );

  /// See [RecordContent.hash].
  static final hash = obx.QueryStringProperty<RecordContent>(
    _entities[2].properties[3],
  );

  /// See [RecordContent.length].
  static final length = obx.QueryIntegerProperty<RecordContent>(
    _entities[2].properties[4],
  );
}
